config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "users#index"
  resources :accounts
  resources :messages
  resources :blogs
  resources :posts
  resources :tasks
  resources :comments, only: %i[create destroy]
  get 'accounts/donwloade/:id', to: "accounts#download", as: "download_icon"
  resources :accounts
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    Blog.create(blog_parameter)
    redirect_to blogs_path
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time)
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

  <div class="予定">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="時間">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="内容">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>


  <div class="確定">
    <%= form.submit %>
  </div>

<% end %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Calendar</h1></center>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to '詳細', blog %></td>
        <td><%= link_to '編集', edit_blog_path(blog.id) %></td>
        <td><%= link_to '削除',blog_path(blog.id), method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<td align="right">
<%= link_to '予定を追加する', new_blog_path %>
</td>
<center>
<%= month_calendar events: @blogs do |date, blogs| %>
  <%= date.day %>

  <% blogs.each do |blog| %>
    <div>
      <%= link_to blog.title, blog %>
    </div>
  <% end %>
<% end %>
</center>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

  <div class="予定">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="時間">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="内容">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>


  <div class="確定">
    <%= form.submit %>
  </div>

<% end %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>時間</strong>
  <%= @blog.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>内容</strong>
  <%= @blog.content %>
</p>

<%= link_to '編集', edit_blog_path(@blog) %> |
<%= link_to '戻る', blogs_path %>